# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edgectl < Formula
  desc "A CLI for edge-cloud"
  homepage "https://github.com/michielvha/edgectl"
  version "0.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.10/edgectl_0.3.10_darwin_amd64.zip"
      sha256 "414dc520c43b95517bf1834c757792839f523e4934a572dbe7502104725e1edd"

      def install
        bin.install "edgectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.10/edgectl_0.3.10_darwin_arm64.zip"
      sha256 "414dc520c43b95517bf1834c757792839f523e4934a572dbe7502104725e1edd"

      def install
        bin.install "edgectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.10/edgectl_0.3.10_linux_amd64.zip"
      sha256 "414dc520c43b95517bf1834c757792839f523e4934a572dbe7502104725e1edd"
      def install
        bin.install "edgectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.10/edgectl_0.3.10_linux_arm64.zip"
      sha256 "414dc520c43b95517bf1834c757792839f523e4934a572dbe7502104725e1edd"
      def install
        bin.install "edgectl"
      end
    end
  end

  test do
    system "#{bin}/edgectl", "--version"
  end
end
