# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edgectl < Formula
  desc "A CLI for edge-cloud"
  homepage "https://github.com/michielvha/edgectl"
  version "0.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.7/edgectl_0.3.7_darwin_amd64.zip"
      sha256 "beb02cee7453c6fcf6cc2f0e7d5964482dc23e9beba4fe4cca58c74062e02903"

      def install
        bin.install "edgectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.7/edgectl_0.3.7_darwin_arm64.zip"
      sha256 "beb02cee7453c6fcf6cc2f0e7d5964482dc23e9beba4fe4cca58c74062e02903"

      def install
        bin.install "edgectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.7/edgectl_0.3.7_linux_amd64.zip"
      sha256 "beb02cee7453c6fcf6cc2f0e7d5964482dc23e9beba4fe4cca58c74062e02903"
      def install
        bin.install "edgectl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/michielvha/edgectl/releases/download/0.3.7/edgectl_0.3.7_linux_arm64.zip"
      sha256 "beb02cee7453c6fcf6cc2f0e7d5964482dc23e9beba4fe4cca58c74062e02903"
      def install
        bin.install "edgectl"
      end
    end
  end

  test do
    system "#{bin}/edgectl", "--version"
  end
end
